- name: Generate release notes with all commit messages per PR
  id: generate_notes
  run: |
    # Get the latest tag
    LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
    echo "Latest tag: $LATEST_TAG"

    # Get merged PRs since last tag (using GitHub CLI)
    PRS_JSON=$(gh pr list --state merged --json number,title --search "merged:>$LATEST_TAG" --repo $GITHUB_REPOSITORY)
    echo "$PRS_JSON" > prs.json

    echo "## What's Changed" > release_notes.md
    echo "" >> release_notes.md

    # Loop through each PR
    for row in $(jq -c '.[]' prs.json); do
      PR_NUMBER=$(echo "$row" | jq -r '.number')
      PR_TITLE=$(echo "$row" | jq -r '.title')

      echo "* $PR_TITLE (PR #$PR_NUMBER)" >> release_notes.md

      # Get all commit messages in this PR
      COMMITS=$(gh pr view $PR_NUMBER --json commits --repo $GITHUB_REPOSITORY --jq '.commits[].commit.message')

      # Indent commit messages under PR title
      while IFS= read -r commit_msg; do
        echo "  - $commit_msg" >> release_notes.md
      done <<< "$COMMITS"

      echo "" >> release_notes.md
    done

    cat release_notes.md

    echo "release_notes<<EOF" >> $GITHUB_OUTPUT
    cat release_notes.md >> $GITHUB_OUTPUT
    echo "EOF" >> $GITHUB_OUTPUT
