name: Create branch per commit

on:
  push:
    branches:
      - main  # or your source branch

jobs:
  create-branch-per-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch full history to access commits

      - name: Get list of new commits in this push
        id: commits
        run: |
          # Get commits in this push (between previous and current)
          # GITHUB_SHA is the latest commit
          # GITHUB_REF is the ref (refs/heads/main)
          PREV_SHA=$(git rev-parse HEAD^)
          echo "Previous SHA: $PREV_SHA"
          echo "Current SHA: $GITHUB_SHA"

          # List commits between PREV_SHA and GITHUB_SHA (inclusive)
          COMMITS=$(git rev-list --reverse $PREV_SHA..$GITHUB_SHA)
          echo "Commits in push:"
          echo "$COMMITS"

          echo "::set-output name=commit_list::$COMMITS"

      - name: Create branches and push commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          for commit in ${{ steps.commits.outputs.commit_list }}; do
            # Create a branch name based on commit SHA
            branch_name="commit-${commit}"

            echo "Creating branch $branch_name for commit $commit"

            # Create branch at that commit
            git branch -f $branch_name $commit

            # Push branch to origin
            git push origin $branch_name --force

            # Optionally create PR via GitHub CLI
            # gh pr create --title "Commit $commit" --body "Auto PR for commit $commit" --base main --head $branch_name --repo $GITHUB_REPOSITORY --draft
          done 