name: 📦 Create Draft Release (Manual)
 
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.2.3)'
        required: true
        type: string
 
jobs:
  update_release_draft:
    name: 🛠 Run Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📝 Extract commit messages from all PRs
        id: extract-commits
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get all merged PRs since last tag
            const { data: recentPulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              sort: 'updated',
              direction: 'desc',
              per_page: 20
            });
            
            const commitData = {};
            
            for (const pr of recentPulls) {
              if (pr.merged_at) {
                try {
                  const { data: commits } = await github.rest.pulls.listCommits({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number
                  });
                  
                  // Extract commit messages with their SHA
                  const commitMessages = commits.map(commit => 
                    `  • ${commit.sha.substring(0, 7)}: ${commit.commit.message.split('\n')[0]}`
                  ).join('\n');
                  
                  commitData[pr.number] = commitMessages || '  • No commit messages available';
                  
                  console.log(`PR #${pr.number}: ${commits.length} commits extracted`);
                  
                } catch (error) {
                  console.error(`Error getting commits for PR #${pr.number}:`, error);
                  commitData[pr.number] = '  • Error fetching commit messages';
                }
              }
            }
            
            // Set output as JSON string
            core.setOutput('commit-data', JSON.stringify(commitData));
            console.log('Total PRs processed:', Object.keys(commitData).length);
            
      - name: 🧰 Run release-drafter with commit data
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ github.event.inputs.version }}
          config-name: release-drafter-commits.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_DATA: ${{ steps.extract-commits.outputs.result }}
