name: ðŸ“¦ Simple Git Commit Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.2.3)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ðŸ“ Get all commits since last tag
        id: get-commits
        run: |
          # Get the previous tag
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
          
          if [ -z "$PREVIOUS_TAG" ]; then
            # If no previous tag, get all commits
            echo "No previous tag found, getting all commits"
            COMMITS=$(git log --oneline --pretty=format:"- %h: %s (%an)" | head -20)
            COMPARE_URL="https://github.com/${{ github.repository }}/releases/tag/v${{ github.event.inputs.version }}"
          else
            # Get commits since last tag
            echo "Getting commits since $PREVIOUS_TAG"
            COMMITS=$(git log $PREVIOUS_TAG..HEAD --oneline --pretty=format:"- %h: %s (%an)")
            COMPARE_URL="https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...v${{ github.event.inputs.version }}"
          fi
          
          # Create release notes
          NOTES="# Release Notes\n\n## Commits\n\n$COMMITS\n\n**Full Changelog**: $COMPARE_URL"
          
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: ðŸš€ Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: ${{ steps.get-commits.outputs.notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
